from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class MaterialSource:
    slug: str
    source_path: Path
    converter: str
    material_group: str
    topic_hint: str
    subtopic_hint: str
    notes: str = ""


def get_material_sources(repo_root: Path) -> list[MaterialSource]:
    materials_root = repo_root.parent / "materials"
    return [
        MaterialSource(
            slug="advance-qa__week-01",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 1 .pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 1",
        ),
        MaterialSource(
            slug="advance-qa__week-02",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 2.pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 2",
        ),
        MaterialSource(
            slug="advance-qa__week-03",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 3.pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 3",
        ),
        MaterialSource(
            slug="advance-qa__week-04",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 4.pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 4",
        ),
        MaterialSource(
            slug="advance-qa__week-05",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 5.pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 5",
        ),
        MaterialSource(
            slug="advance-qa__week-06",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 6.pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 6",
        ),
        MaterialSource(
            slug="advance-qa__week-07",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 7.pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 7",
        ),
        MaterialSource(
            slug="advance-qa__week-08",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 8.pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 8",
        ),
        MaterialSource(
            slug="advance-qa__week-09",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 9.pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 9",
        ),
        MaterialSource(
            slug="advance-qa__week-10",
            source_path=materials_root / "ADVANCE Q&A-20260126T193115Z-3-001" / "WEEK 10.pdf",
            converter="mcq",
            material_group="advance-qa",
            topic_hint="Sanitation, Plumbing Design and Installation",
            subtopic_hint="Advance Q&A Week 10",
        ),
        MaterialSource(
            slug="plumbing-arithmetic__terms-01",
            source_path=materials_root / "PLUMBING ARITHMETIC-20260126T193107Z-3-001" / "PA - TERMS 1.pdf",
            converter="mcq",
            material_group="plumbing-arithmetic",
            topic_hint="Plumbing Arithmetic",
            subtopic_hint="Terms 1",
            notes="OCR-heavy question bank.",
        ),
        MaterialSource(
            slug="plumbing-arithmetic__terms-02",
            source_path=materials_root / "PLUMBING ARITHMETIC-20260126T193107Z-3-001" / "PA - TERMS 2.pdf",
            converter="mcq",
            material_group="plumbing-arithmetic",
            topic_hint="Plumbing Arithmetic",
            subtopic_hint="Terms 2",
            notes="OCR-heavy question bank.",
        ),
        MaterialSource(
            slug="plumbing-arithmetic__terms-03",
            source_path=materials_root / "PLUMBING ARITHMETIC-20260126T193107Z-3-001" / "PA - TERMS 3.pdf",
            converter="mcq",
            material_group="plumbing-arithmetic",
            topic_hint="Plumbing Arithmetic",
            subtopic_hint="Terms 3",
            notes="OCR-heavy question bank.",
        ),
        MaterialSource(
            slug="plumbing-arithmetic__terms-04",
            source_path=materials_root / "PLUMBING ARITHMETIC-20260126T193107Z-3-001" / "PA - TERMS 4.pdf",
            converter="mcq",
            material_group="plumbing-arithmetic",
            topic_hint="Plumbing Arithmetic",
            subtopic_hint="Terms 4",
            notes="OCR-heavy question bank.",
        ),
        MaterialSource(
            slug="terms-numbers__aspe-terminology",
            source_path=materials_root / "TERMS & NUMBERS-20260126T193044Z-3-001" / "ASPE PLUMBING TERMINOLOGY.pdf",
            converter="facts",
            material_group="terms-numbers",
            topic_hint="Plumbing Terminology",
            subtopic_hint="ASPE Definitions",
        ),
        MaterialSource(
            slug="terms-numbers__important-numbers",
            source_path=materials_root / "TERMS & NUMBERS-20260126T193044Z-3-001" / "IMPORTANT NUMBERS.pdf",
            converter="facts",
            material_group="terms-numbers",
            topic_hint="Code Memory",
            subtopic_hint="Important Numbers",
        ),
        MaterialSource(
            slug="terms-numbers__code-summary",
            source_path=materials_root / "TERMS & NUMBERS-20260126T193044Z-3-001" / "PLUMBING CODE SUMMARY.pdf",
            converter="facts",
            material_group="terms-numbers",
            topic_hint="Plumbing Code",
            subtopic_hint="Code Summary",
        ),
        MaterialSource(
            slug="terms-numbers__practical-problem-terms",
            source_path=materials_root / "TERMS & NUMBERS-20260126T193044Z-3-001" / "PRACTICAL PROBLEM TERMS.pdf",
            converter="facts",
            material_group="terms-numbers",
            topic_hint="Practical Problems",
            subtopic_hint="Terms",
        ),
        MaterialSource(
            slug="tables__astm-nfpa",
            source_path=materials_root / "TABLES-20260126T193053Z-3-001" / "1. ASTM-NFPA.pdf",
            converter="facts",
            material_group="tables",
            topic_hint="Codes and Standards",
            subtopic_hint="ASTM and NFPA",
        ),
        MaterialSource(
            slug="tables__laws-rules-regulations",
            source_path=materials_root / "TABLES-20260126T193053Z-3-001" / "2. LAWS, RULES AND REGULATIONS AFFECTING THE PLUMBING PROFESSION.pdf",
            converter="facts",
            material_group="tables",
            topic_hint="Laws and Regulations",
            subtopic_hint="Profession",
        ),
        MaterialSource(
            slug="tables__plumbing-tables-jam",
            source_path=materials_root / "TABLES-20260126T193053Z-3-001" / "3. PLUMBING TABLES by JAM.pdf",
            converter="facts",
            material_group="tables",
            topic_hint="Plumbing Tables",
            subtopic_hint="JAM Tables",
        ),
        MaterialSource(
            slug="tables__plumbing-tools-reference",
            source_path=materials_root / "TABLES-20260126T193053Z-3-001" / "4. PLUMBING TOOLS ALL REFERENCE.pdf",
            converter="facts",
            material_group="tables",
            topic_hint="Plumbing Tools",
            subtopic_hint="Reference",
        ),
        MaterialSource(
            slug="tables__useful-conversions",
            source_path=materials_root / "TABLES-20260126T193053Z-3-001" / "5. USEFUL CONVERSIONS.pdf",
            converter="facts",
            material_group="tables",
            topic_hint="Plumbing Arithmetic",
            subtopic_hint="Useful Conversions",
        ),
        MaterialSource(
            slug="spdi__water-supply-distribution",
            source_path=materials_root / "SPDI-20260126T193056Z-3-001" / "1. Water Supply & Distribution Principles.pdf",
            converter="facts",
            material_group="spdi",
            topic_hint="Water Supply Systems",
            subtopic_hint="Distribution Principles",
        ),
        MaterialSource(
            slug="spdi__plumbing-materials",
            source_path=materials_root / "SPDI-20260126T193056Z-3-001" / "2. Plumbing Materials.pdf",
            converter="facts",
            material_group="spdi",
            topic_hint="Plumbing Materials",
            subtopic_hint="Materials",
        ),
        MaterialSource(
            slug="spdi__accessibility-law",
            source_path=materials_root / "SPDI-20260126T193056Z-3-001" / "3. Accessibility Law.pdf",
            converter="facts",
            material_group="spdi",
            topic_hint="Accessibility Law",
            subtopic_hint="Law Summary",
        ),
        MaterialSource(
            slug="reference__revised-national-plumbing-code",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "1. Revised National Plumbing Code of the Philippines.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Revised National Plumbing Code",
            subtopic_hint="Reference Book",
        ),
        MaterialSource(
            slug="reference__illustrated-national-plumbing-code",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "1A. Illustrated National Plumbing Code of the Philippines.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Illustrated Plumbing Code",
            subtopic_hint="Reference Book",
        ),
        MaterialSource(
            slug="reference__plumbing-design-estimate-fajardo",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "2. Plumbing Design and Estimate by Max Fajardo.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Plumbing Design and Estimate",
            subtopic_hint="Max Fajardo",
        ),
        MaterialSource(
            slug="reference__ra-1378-plumbing-law",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "3. RA-1378-Plumbing-Law.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Plumbing Law",
            subtopic_hint="RA 1378",
        ),
        MaterialSource(
            slug="reference__ra-1364-sanitary-engineering-law",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "4. RA-1364-Sanitary-Engineering-Law.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Sanitary Engineering Law",
            subtopic_hint="RA 1364",
        ),
        MaterialSource(
            slug="reference__ridgid-catalogue",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "5. Ridgid Catalogue.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Plumbing Tools",
            subtopic_hint="Ridgid Catalogue",
        ),
        MaterialSource(
            slug="reference__audel-pocket-manual",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "6. AUDEL Plumbers Pocket Manual 10th Edition.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Plumber's Pocket Manual",
            subtopic_hint="AUDEL",
        ),
        MaterialSource(
            slug="reference__audel-questions-answers",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "7. AUDEL Questions and Answers for Plumbers Examination 4th Edition.pdf",
            converter="mcq",
            material_group="reference-books",
            topic_hint="Plumber Examination Questions",
            subtopic_hint="AUDEL Questions and Answers",
            notes="Large text-native question bank.",
        ),
        MaterialSource(
            slug="reference__fundamentals-of-plumbing-engineering",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "8. Fundamentals of Plumbing Engineering by ASPE.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Fundamentals of Plumbing Engineering",
            subtopic_hint="ASPE",
        ),
        MaterialSource(
            slug="reference__plumbing-engineering-design",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "9. Plumbing Engineering Design by ASPE.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Plumbing Engineering Design",
            subtopic_hint="ASPE",
        ),
        MaterialSource(
            slug="reference__plumbing-arithmetic-book",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "10. Plumbing Arithmetic_.pdf",
            converter="mcq",
            material_group="reference-books",
            topic_hint="Plumbing Arithmetic",
            subtopic_hint="Reference Book",
            notes="OCR-heavy question bank.",
        ),
        MaterialSource(
            slug="reference__drinking-water-standards",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "11. Philippine National Standards for Drinking Water - PNSDW 2007.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Drinking Water Standards",
            subtopic_hint="PNSDW 2007",
        ),
        MaterialSource(
            slug="reference__bp344-amended-irr",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "12. AMENDED IRR BP344- OFFICIAL GAZETTE.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Accessibility Regulations",
            subtopic_hint="BP344",
        ),
        MaterialSource(
            slug="reference__green-building-code",
            source_path=materials_root / "REFERENCE BOOKS-20260126T193100Z-3-001" / "13. PH GREEN BUILDING CODE.pdf",
            converter="facts",
            material_group="reference-books",
            topic_hint="Green Building Code",
            subtopic_hint="Code Summary",
        ),
    ]
